defaults:
  - _self_
  - experiment: brca

method: original

paths:
  ppi: data_set/ppi_network/HIPPIE.tsv
  ontology_network: data_set/ontology_network/ontology_network.tsv
  gene_similarity: knowledge/gene_similarity_network(1).csv

params:
  restart_prob: 0.9
  alpha: 0.5
  beta: 0.5

evaluation:
  mode: fixed   # dynamic

  fixed:
    k: [100, 200]

  dynamic:
    c_values: [8, 16]
    k_max: 1500